"""
Bazel rules for building Quarkus extensions.

Quarkus extensions follow a runtime/deployment split pattern:
- Runtime: Code available at application runtime
- Deployment: Build-time augmentation code
"""

load("@rules_java//java:defs.bzl", "java_library", "java_plugin")
load("//bazel/rules:jandex.bzl", "jandex_index")

def _quarkus_extension_metadata_impl(ctx):
    """Generates quarkus-extension.properties metadata file."""
    output = ctx.actions.declare_file(
        "META-INF/quarkus-extension.properties",
    )

    content = """# Generated by Bazel
deployment-artifact={deployment_artifact}
""".format(
        deployment_artifact = ctx.attr.deployment_artifact,
    )

    ctx.actions.write(
        output = output,
        content = content,
    )

    return [DefaultInfo(files = depset([output]))]

_quarkus_extension_metadata = rule(
    implementation = _quarkus_extension_metadata_impl,
    attrs = {
        "deployment_artifact": attr.string(
            mandatory = True,
            doc = "Maven coordinates of the deployment artifact",
        ),
    },
)

def quarkus_extension_runtime(
        name,
        srcs,
        resources = [],
        deps = [],
        runtime_deps = [],
        exports = [],
        plugins = [],
        javacopts = [],
        deployment_artifact = None,
        visibility = None,
        tags = [],
        **kwargs):
    """
    Builds a Quarkus extension runtime module.

    Runtime modules contain code that is available at application runtime.
    They should be lightweight and contain only runtime dependencies.

    Args:
        name: Name of the runtime library
        srcs: Java source files
        resources: Resource files to include
        deps: Compile-time dependencies
        runtime_deps: Runtime-only dependencies
        exports: Dependencies to re-export
        plugins: Java annotation processors
        javacopts: Additional Java compiler options
        deployment_artifact: Maven coordinates of the deployment module
        visibility: Target visibility
        tags: Build tags
        **kwargs: Additional arguments passed to java_library
    """

    # Generate extension metadata if deployment artifact specified
    metadata_name = name + "_metadata"
    if deployment_artifact:
        _quarkus_extension_metadata(
            name = metadata_name,
            deployment_artifact = deployment_artifact,
            tags = tags + ["manual"],
        )

        # Include metadata in resources
        resources = resources + [":" + metadata_name]

    # Add Quarkus extension processor plugin
    processor_plugin_name = name + "_processor"
    java_plugin(
        name = processor_plugin_name,
        processor_class = "io.quarkus.extension.gradle.QuarkusExtensionProcessor",
        deps = [
            "@maven//:io_quarkus_quarkus_extension_processor",
        ] if "@maven//:io_quarkus_quarkus_extension_processor" else [],
        tags = tags + ["manual"],
    )

    # Generate Jandex index
    jandex_name = name + "_jandex"
    jandex_index(
        name = jandex_name,
        deps = deps,
        tags = tags + ["manual"],
    )

    # Build the runtime library
    java_library(
        name = name,
        srcs = srcs,
        resources = resources + [":" + jandex_name],
        deps = deps + [
            "@maven//:jakarta_enterprise_jakarta_enterprise_cdi_api",
            "@maven//:jakarta_inject_jakarta_inject_api",
            "@maven//:jakarta_annotation_jakarta_annotation_api",
            "@maven//:org_jboss_logging_jboss_logging",
        ],
        runtime_deps = runtime_deps,
        exports = exports,
        plugins = plugins + [":" + processor_plugin_name],
        javacopts = javacopts + [
            "-parameters",  # Required by Quarkus for parameter name reflection
        ],
        visibility = visibility,
        tags = tags,
        **kwargs
    )

def quarkus_extension_deployment(
        name,
        srcs,
        resources = [],
        deps = [],
        runtime_deps = [],
        exports = [],
        plugins = [],
        javacopts = [],
        runtime_module = None,
        visibility = None,
        tags = [],
        **kwargs):
    """
    Builds a Quarkus extension deployment module.

    Deployment modules contain build-time augmentation code that processes
    the application and generates optimized bytecode. They are not included
    in the final application.

    Args:
        name: Name of the deployment library
        srcs: Java source files
        resources: Resource files
        deps: Compile-time dependencies
        runtime_deps: Runtime-only dependencies
        exports: Dependencies to re-export
        plugins: Java annotation processors
        javacopts: Additional Java compiler options
        runtime_module: The corresponding runtime module
        visibility: Target visibility
        tags: Build tags
        **kwargs: Additional arguments passed to java_library
    """

    deployment_deps = deps + [
        # Core deployment dependencies
        "@maven//:io_quarkus_gizmo_gizmo",
        "@maven//:io_smallrye_jandex",
        "@maven//:org_ow2_asm_asm",
        "@maven//:org_ow2_asm_asm_commons",
        "@maven//:org_jboss_logging_jboss_logging",
    ]

    # Add runtime module as dependency if specified
    if runtime_module:
        deployment_deps.append(runtime_module)

    # Build the deployment library
    java_library(
        name = name,
        srcs = srcs,
        resources = resources,
        deps = deployment_deps,
        runtime_deps = runtime_deps,
        exports = exports,
        plugins = plugins,
        javacopts = javacopts + [
            "-parameters",
        ],
        visibility = visibility,
        tags = tags,
        **kwargs
    )

def quarkus_extension(
        name,
        runtime_srcs = [],
        runtime_resources = [],
        runtime_deps = [],
        runtime_exports = [],
        deployment_srcs = [],
        deployment_resources = [],
        deployment_deps = [],
        deployment_exports = [],
        shared_deps = [],
        visibility = None,
        tags = []):
    """
    Convenience macro to build both runtime and deployment modules.

    This macro creates two targets:
    - {name}-runtime: The runtime module
    - {name}-deployment: The deployment module

    Args:
        name: Base name for the extension
        runtime_srcs: Runtime Java sources
        runtime_resources: Runtime resources
        runtime_deps: Runtime dependencies
        runtime_exports: Runtime exports
        deployment_srcs: Deployment Java sources
        deployment_resources: Deployment resources
        deployment_deps: Deployment dependencies
        deployment_exports: Deployment exports
        shared_deps: Dependencies shared by both runtime and deployment
        visibility: Target visibility
        tags: Build tags
    """

    runtime_name = name + "-runtime"
    deployment_name = name + "-deployment"

    # Build runtime module
    quarkus_extension_runtime(
        name = runtime_name,
        srcs = runtime_srcs,
        resources = runtime_resources,
        deps = runtime_deps + shared_deps,
        exports = runtime_exports,
        deployment_artifact = "io.quarkus:%s:999-SNAPSHOT" % deployment_name,
        visibility = visibility,
        tags = tags,
    )

    # Build deployment module
    quarkus_extension_deployment(
        name = deployment_name,
        srcs = deployment_srcs,
        resources = deployment_resources,
        deps = deployment_deps + shared_deps,
        exports = deployment_exports,
        runtime_module = ":" + runtime_name,
        visibility = visibility,
        tags = tags,
    )
